name: Master
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"

      - name: Create npmrc
        run: |
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}' >> .npmrc
          echo '@ashkanjj:registry=https://npm.pkg.github.com/' >> .npmrc
          npm ci

      - name: build all
        run: |
          npm run build --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  planAndDeploy:
    runs-on: ubuntu-latest
    name: Plan and deploy
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: |
          terraform init -reconfigure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}

      - name: Terrraform validate
        continue-on-error: true
        run: |
          terraform fmt -check

      - name: Terrraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        run: |
          terraform plan -input=false -refresh=true -out=plan.out
