name: Master
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Create npmrc
        run: |
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}' >> .npmrc
          echo '@ashkanjj:registry=https://npm.pkg.github.com/' >> .npmrc
          pwd
      - name: is the file there
        run: |
          ls -la
          echo ${{ github.workspace }}
          echo "${{ github.workspace }}"
          cat .npmrc
      - name: build all
        run: |
          pwd
          cd src/lambdas/get_watcher
          npm ci
          npm build
          cd src/lambdas/register_watcher
          npm ci
          npm build
